export const ROOT_NAME = "ROOT_NAME";
export const CREATE_FACTORY = "CREATE_FACTORY";
export const GET_FACTORIES = "GET_FACTORIES";
export const GET_FACTORY = "GET_FACTORY";
export const DELETE_FACTORY = "DELETE_FACTORY";
export const EDIT_FACTORY = "EDIT_FACTORY";
